### ISSUE TITLE
キル不能状態関連の不具合について

### ISSUE THREAD

**Issue by tomarai** [AUModS/AUModS#24]
# 報告内容
> 昇降機付近でキル出来ない事があるので、一旦はしごでのキルされない様にする設定外してもらう事出来ますか？

# 該当箇所
https://www.youtube.com/watch?v=89p1EYxk5a4&t=3329s

**Comment by tomarai** [comment]
#20 との関係性を疑われていました
自分のほうで調査したところ無関係なのは確認済みです

お手数ですが @Hyz-sui さんも確認していただけますか？

**Comment by Hyz-sui** [comment]
昇降機周辺でキルできない事象については，視聴していた限りでは以前から発生していたはずなので，やはり間違いなく #20 は関係なさそうに思われます．
また，仮にはしごが原因だった場合，プレイ中の各はしごの使用頻度も鑑みるとある程度電気室周辺でも同様の事象が発生するはずですから，あまり考えにくいです．
`CheckMurder`のパッチは #20 のみのはずですから，バニラ起因の可能性があると思います．

昇降機周辺で頻発するということは昇降機のプラットフォームが何か影響しているかもしれないと思いましたが，例に挙げられている回のキル対象である[桃＋さんの視点](https://youtu.be/gvUt0nwQrHw?t=3288)を確認したところ，そのターンでは昇降機に乗っていないようでした．
仮に以前のターンに昇降機に乗ったことが影響する場合，キル自体の発生場所は関係ありませんから奇妙に思います．

関係の有無は不明ですが，[当該ターンの1つ前のターンの桃＋さん視点](https://youtu.be/gvUt0nwQrHw?t=3116)に，桃＋さんが昇降機で左から右に移動した後，右から左に移動しようと使用ボタンを押すも乗れない(たけぉさんに先を越される)場面がありましたので，もしかしたら関係があるかもしれません．

いずれにしても，特定のターゲットに対してキルができない原因としてはCheckMurderの処理内容から
1. ターゲットが既に死亡判定になっている
2. `target`や`target.Data`がnullである
3. ターゲットがベント内にいる
4. ターゲットが昇降機に乗っている

が考えられますが，1や2はもっと重大なバグが発生するはずであること，3は対象がクルーメイトであることから除外できると考えているので，基本的に`inMovingPlat`が関係していると見てよいと思っています．

**Comment by tomarai** [comment]
了解です
なんか噂程度で申し訳ないですが，他にも様々なケースでボタンは有効なのにキルが発生しないことがあるみたいなので必ずしも `inMovingPlat` ではないのかなとも思っています．
いずれにせよ本格的に明らかにしたい場合は `CheckMurder` のところにログを仕込んでおくのが良さそうですね（自分はやる予定はないです）

**Comment by tomarai** [comment]
また，これに関してコードを読んでいて思ったのですが， `onLadder` が `true` の状態で meeting に呼ばれると `onLadder` は次のはしご昇降を行うまで true になりつづけるのではないかと思います．
そこの状態管理は大丈夫でしょうか？

**Comment by tomarai** [comment]
> また，これに関してコードを読んでいて思ったのですが， `onLadder` が `true` の状態で meeting に呼ばれると `onLadder` は次のはしご昇降を行うまで true になりつづけるのではないかと思います． そこの状態管理は大丈夫でしょうか？

この場合はたしかにキル不能になることが確認できました

**Comment by tomarai** [comment]
正しい修正は `onLadder` の管理方法を直すことだとは思いますが、今回は CheckMurderPatch を revert することで対処しておきました

**Comment by Hyz-sui** [comment]
なんと、そんなバグがあったのですね
調査と対応ありがとうございます
今回例に挙がっているケースも直前のターンではしごから降りた瞬間に会議が始まっているようなのでホストの高田さん視点で`onLadder`がtrueのまま会議に突入していた可能性は十分にありそうです

`CheckMurderPatch`についてですが、やはりはしごキルは何度も発生していたこともあり、対策はしておいたほうが良いと思っているのですが、いかがでしょうか
その場合、`PlayerControl.ResetForMeeting`か`PlayerPhysics.ResetMoveState`あたり(後者は色々巻き込んでいるようなので前者の方が良いと思っています)にパッチして`onLadder`をfalseに戻す処理を追加するような形で考えています

**Comment by Hyz-sui** [comment]
キル不能に関してはバニラスケルドでキルができない事象[(プテはしさん視点アーカイブ)](https://youtu.be/wsd-pM3FRFU?t=2794)が以前発生していたのを思い出しました．
スケルドにははしごも昇降機もありませんから，何か他に原因がある，もしくは複数の異なる原因からキル不能が発生している可能性は確かにありそうです

**Comment by tomarai** [comment]
> `CheckMurderPatch`についてですが、やはりはしごキルは何度も発生していたこともあり、対策はしておいたほうが良いと思っているのですが、いかがでしょうか 

対策に関しては開発者の熱意次第かなと思います（個人的には皆無です）
熱心に対策したいという開発者の人がいたら自分は付き合うというスタンスです
ゲーム本体側で対策しないとどうしても今回のように他変数の管理手法で問題になることもありますし，ゲーム本体の変更に ad hoc に対応しないといけないというところも個人的にはマイナスポイントです

> その場合、`PlayerControl.ResetForMeeting`か`PlayerPhysics.ResetMoveState`あたり(後者は色々巻き込んでいるようなので前者の方が良いと思っています)にパッチして`onLadder`をfalseに戻す処理を追加するような形で考えています

ここは同意です． `onLadder` が PlayerControl のメンバである以上， `PlayerControl.ResetForMeeting` の postfix で `onLadder` の値を更新するのが一番正しいと思います

> キル不能に関してはバニラスケルドでキルができない事象[(プテはしさん視点アーカイブ)](https://youtu.be/wsd-pM3FRFU?t=2794)が以前発生していたのを思い出しました．
スケルドにははしごも昇降機もありませんから，何か他に原因がある，もしくは複数の異なる原因からキル不能が発生している可能性は確かにありそうです

この二つのケースだけを見ると， どちらのケースもキル不能になったインポスターは既にキルされているプレイヤーをターゲットにとってキルのリクエストを送っているように見えますね

**Comment by Hyz-sui** [comment]
ありがとうございます．お手間を取らせることになってしまうかもしれませんが，`onLadder`の更新を追加するのみで良さそうですので今後再びPRを出させていただくかもしれません．

> この二つのケースだけを見ると， どちらのケースもキル不能になったインポスターは既にキルされているプレイヤーをターゲットにとってキルのリクエストを送っているように見えますね

プテさんのケースはともかく，最初に例に挙げられていた高田さんのケースでは高田さんはホストですが，既にキルされているプレイヤーに対してホストがキルを行う状況ってあり得るのでしょうか？ 私の理解では，ホストである高田さんがキルボタンを押した時点で，高田さんによるキルの判定が即行われて対象のキャラクターが死亡し，非ホストのふじみやさんによるキルリクエストが`CheckMurder`によって弾かれると思っていました．
また，スロー再生でキルのターゲットを示す赤いアウトラインとキルボタンの点滅を確認した限りでは，高田さんがベントから出た直後こそさかなさん(ふじみやさんがキル)にターゲットが向いていますが，そこから昇降機左のリアクター修復コンソール前まで移動した時点で桃＋さんにアウトラインが移り，それまでの間はキルボタンを押していないように見えました．[ふじみやさん視点](https://youtu.be/vawuAwwNwTY?t=3308)でも，ふじみやさんはさかなさんにしかキルを行っていないように見えました．

**Comment by tomarai** [comment]
> ありがとうございます．お手間を取らせることになってしまうかもしれませんが，onLadderの更新を追加するのみで良さそうですので今後再びPRを出させていただくかもしれません．

了解です PR 前にドッグフーディングだけお願いします

>  私の理解では，ホストである高田さんがキルボタンを押した時点で，高田さんによるキルの判定が即行われて対象のキャラクターが死亡し，非ホストのふじみやさんによるキルリクエストがCheckMurderによって弾かれると思っていました．

これに関しては RPC の処理と target を更新する処理と click イベントの処理の実行順序によると思います
target の更新後から click イベントを処理するまでの間に RPC の処理が入り込む余地がないのであれば Hyz-sui さんの言う通りかと思います

> また，スロー再生でキルのターゲットを示す赤いアウトラインとキルボタンの点滅を確認した限りでは，高田さんがベントから出た直後こそさかなさん(ふじみやさんがキル)にターゲットが向いていますが，そこから昇降機左のリアクター修復コンソール前まで移動した時点で桃＋さんにアウトラインが移り，それまでの間はキルボタンを押していないように見えました．[ふじみやさん視点](https://youtu.be/vawuAwwNwTY?t=3308)でも，ふじみやさんはさかなさんにしかキルを行っていないように見えました．

たしかに このケースは Hyz-sui さんの言う通りレースコンディションではなさそうな気もします
この辺のちょっとした映像だけ見て考えても無駄が多そうなので，情報が集まった時にまた考えます

**Comment by Hyz-sui** [comment]
映っていないので不確かではありますが，3月2日のケースは https://github.com/AUModS/AUModS/issues/24#issuecomment-1454507383 の通り`onLadder`のバニラバグ起因に見えています
他のキル不能事象も記憶を頼りに探してみましたが見つけられませんでした
今後は少しキル不能事象に気を払いながら視聴してみます
各村の皆様との連絡がどのようになっているのかわからないのですが，もしキル不能事象が発生したシーンがあった際はこちらに報告したほうがよいでしょうか？

**Comment by tomarai** [comment]
この辺の結果に関してはログがない以上なんとも言えないというのが自分の結論です
ソフトウェア開発に詳しくない人たちに勝手に原因を思い込まれると色々と煩わしいので......

> 各村の皆様との連絡がどのようになっているのかわからないのですが，もしキル不能事象が発生したシーンがあった際はこちらに報告したほうがよいでしょうか？

ゲーム本体の問題ですので，自分からなにかすることはないです．
それゆえ，連絡の必要はありません．ありがとうございます

**Comment by Hyz-sui** [comment]
承知しました。個人的に原因に興味があるので勝手に調べてみます
詳しくは知りませんが、今回のアップデートでキル周りの仕様が変わったという話を耳にしたので、それで何か変わっていれば……といった感じです
色々と長引かせてしまって申し訳ないです

**Comment by tomarai** [comment]
いえ，バグ調査 & 開発上の疑問で長引くことは何も問題ありません！
今後ともよろしくお願いいたします
